### Volume Control ###
volume-max=250.000
volume=120.000

### Appearances ###
border=no
msg-color=yes
msg-module=yes
osd-duration=2000
osd-bar=no
osd-on-seek=no

### Preferences ###
audio-display=no
save-position-on-quit

### Video Decoding ###
hwdec=auto

### Audio Tuning ###
alang=ja,en
audio-samplerate=48000

### Subtitles ###
slang=ja,en

### Profiles ###
[music]
profile-desc=Play a music album directory under the ~/Music
profile-cond=path:find('Music')
video=no
resume-playback=no
directory-filter-types-set=audio
replaygain=album
