[flags]
# Shows GPU(s) information
enable_gpu = true

# Processes widget configuration
[processes]
columns = ["Name", "CPU%", "Mem%", "R/s", "W/s", "T.Read", "T.Write", "GMem%", "GPU%"]

# Disk widget configuration
[disk.mount_filter]
is_list_ignored = true
list = ["/var/.*", "/boot", "/boot/efi", "/srv", "/root", "/home"]
regex = true
case_sensitive = false
whole_word = false

# Temperature widget description
# k10temp: tccd1 - Tdie1 temp of AMD CPU
# k10temp: tctl - CCD temp of AMD CPU (Almost core tempeture)
# r8169-0-900:00 - Realtek RTL8125 2.5GbE (マザーのインターフェイス)
# thermal_zone0 (iwlwifi_1) - Intel Wi-Fi 6 AX200 (Wi-Fiカード)

 # Temperature widget configuration
[temperature]
[temperature.sensor_filter]
is_list_ignored = true
list = ["k10temp: Tccd1"]
regex = false
case_sensitive = true
whole_word = true

# Theme configuration
theme = "default"

# Use custom theme as default theme
### kanagawa-dragon ###
[styles.cpu]
all_entry_color = "#8a9a7b"
avg_entry_color = "#c4746e"
cpu_core_colors = ["#938AA9", "#E6C384", "#7AA89F", "#7AA89F", "#7FB4CA", "#7AA89F", "#7AA89F", "#7FB4CA"]

[styles.memory]
ram_color = "#938AA9"
cache_color = "#E46876"
swap_color = "#E6C384"
arc_color = "#7AA89F"
gpu_colors = ["#7FB4CA", "#E46876", "#8ea4a2", "#8a9a7b", "#8ba4b0", "#c4746e"]

[styles.network]
rx_color = "#938AA9"
tx_color = "#E6C384"
rx_total_color = "#7AA89F"
tx_total_color = "#7AA89F"

[styles.battery]
high_battery_color = "#8a9a7b"
medium_battery_color = "#c4b28a"
low_battery_color = "#c4746e"

[styles.tables]
headers = {color = "#7FB4CA", bold = true}

[styles.graphs]
graph_color = "#727169"
legend_text = {color = "#727169"}

[styles.widgets]
border_color = "#727169"
selected_border_color = "#7FB4CA"
widget_title = {color = "#727169"}
text = {color = "#727169"}
selected_text = {color = "#C8C093", bg_color = "#2D4F67"}
disabled_text = {color = "#717C7C"}  # katanaGray

