[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lineLength = 79

[language-server.ruff.config.settings.lint]
extendSelect = ["UP", "ANN", "ASYNC", "I", "N", "C4", "D"]
ignore = ["E501", "ANN101", "ANN102", "D203", "D213"]
preview = false  # unstable rules and fixes

[language-server.pyright.config.python.alalysis]
autoSearchPaths = true
typeCheckingMode = "strict"
