[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501,ANN101,ANN102,D203,D213", "--extend-select", "UP,ANN,ASYNC,I,N,C4,D"]
