[general]  ### Since alacritty 0.14.0-dev (60677877) ### See <https://github.com/alacritty/alacritty/commit/51089cfeed1adfd741d8dcbe6c9cb9376f88a576> ###
import = [ 
  "synthwave_84.toml",
  # "themes/catppuccin_mocha.toml",
  # "themes/themes/nightfox",
  # "themes/themes/nord",
]

live_config_reload = true

[terminal] ### Since alacritty 0.14.0-dev (60677877) ### See <https://github.com/alacritty/alacritty/commit/51089cfeed1adfd741d8dcbe6c9cb9376f88a576> ###
shell = "fish"

[font]
size = 16.0

[font.normal]
# family = "Cascadia Next JP"
family = "Moralerspace Neon HWNF"

[window]
# opacity = 0.85
blur = false
dimensions = { columns = 162, lines = 40 }
dynamic_padding = true
# decorations = "None"  # None | Full
startup_mode = "Windowed"  # "Windowed" | "Maximized" | "Fullscreen"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 15
thickness = 0.3
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[colors]
transparent_background_colors = true

[mouse]
hide_when_typing = true
