import = [ 
  "themes/themes/kanagawa_dragon.toml",
  "themes/themes/nightfox",
  "themes/themes/night_owl",
  "themes/themes/nord",
]

live_config_reload = true

shell = "fish"

[font]
size = 18.0

[font.normal]
# family = "Moralerspace Radon NF"
family = "Moralerspace Radon HWNF"

[window]
opacity = 0.85
blur = false
dimensions = { columns = 194, lines = 48 }
padding = { x = 4, y = 0 }
dynamic_padding = true
decorations = "None"  # None | Full
startup_mode = "Windowed"  # "Windowed" | "Maximized" | "Fullscreen"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 15
thickness = 0.2
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[colors]
transparent_background_colors = true

[mouse]
hide_when_typing = true
