live_config_reload = true

shell = "fish"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.7
blur = false
decorations = "None"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 15
thickness = 0.2

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true
