import = [ "~/.config/alacritty/themes/themes/kanagawa_dragon.toml" ]
# import = [ "~/.config/alacritty/themes/themes/night_owl.toml" ]
# import = [ "~/.config/alacritty/themes/themes/nord.toml" ]

live_config_reload = true

shell = "fish"

[font]
size = 18.0

[font.normal]
family = "Moralerspace Radon NF"

[window]
opacity = 0.6
blur = false
decorations = "None"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 15
thickness = 0.2

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true
