live_config_reload = true

shell = "fish"

[font]
size = 18.0

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "MonaspiceAr Nerd Font"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.75
blur = false

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 120
lines = 30

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 0
thickness = 0.2

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
action = "SpawnNewInstance"
