[general]
import = [ 
  # "themes/themes/nord.toml",
  "themes/themes/kanagawa_dragon.toml",
  # "themes/themes/catppuccin_mocha.toml",
  # "themes/themes/synthwave_84.toml",
]
live_config_reload = true

[env]
# TERM = "xterm-256color"  # For SSH compatibility issue
WINIT_X11_SCALE_FACTOR = "1"

[window]
title = "Alacritty@CachyOS"
# dimensions = { columns = 150, lines = 38 }
decorations = "None"  # None | Full
opacity = 0.85
blur = false
startup_mode = "Maximized"  # "Windowed" | "Maximized" | "Fullscreen"

[window.class]
instance = "Alacritty"
general = "Alacritty"

[font]
normal = { family = "UDEV Gothic 35NFLG", style = "Regular" }
bold = { family = "UDEV Gothic 35NFLG", style = "Regular" }
italic = { family = "UDEV Gothic 35NFLG", style = "Regular" }
size = 18.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_timeout = 15
unfocused_hollow = false
thickness = 0.3

[terminal]
shell = { program = "/usr/bin/fish", args = [] }

[mouse]
hide_when_typing = true
