[general]
live_config_reload = true
# import = [ "./themes/themes/kanagawa_dragon.toml" ]

[window]
title = "Alacritty@CachyOS"
decorations = "None"  # None | Full
startup_mode = "Maximized"  # "Windowed" | "Maximized" | "Fullscreen"
opacity = 0.75

[window.class]
instance = "Alacritty"
general = "Alacritty"

[font]
# normal = { family = "Moralerspace Radon HW", style = "Regular" }
normal = { family = "IosevkaTerm NF", style = "Regular" }
size = 18.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_timeout = 5
unfocused_hollow = false
thickness = 0.3

[terminal]
shell = { program = "/usr/bin/fish" }

[mouse]
hide_when_typing = true
