[general]
import = [ 
  # "themes/themes/nord.toml",
  "themes/themes/catppuccin_mocha.toml",
  # "themes/themes/synthwave_84.toml",
]
live_config_reload = true

[window]
dimensions = { columns = 150, lines = 38 }
decorations = "Full"  # None | Full
opacity = 0.9
blur = false
startup_mode = "Windowed"  # "Windowed" | "Maximized" | "Fullscreen"

[font]
normal = { family = "Moralerspace Radon HWNF", style = "Regular" }
bold = { family = "Moralerspace Radon HWNF", style = "Regular" }
italic = { family = "Moralerspace Radon HWNF", style = "Regular" }
size = 16.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_timeout = 15
unfocused_hollow = false
thickness = 0.3

[terminal]
shell = { program = "/usr/bin/fish", args = [] }

[mouse]
hide_when_typing = true
