[general]
import = [ 
  "themes/themes/kanagawa_dragon.toml",
  # "themes/themes/kanagawa_wave.toml",
  # "themes/themes/catppuccin_mocha.toml",
]
live_config_reload = true

[env]
# TERM = "xterm-256color"  # For SSH compatibility issue
WINIT_X11_SCALE_FACTOR = "1"

[window]
title = "Alacritty@CachyOS"
# dimensions = { columns = 148, lines = 40 }
decorations = "None"  # None | Full
opacity = 0.85
# blur = true
startup_mode = "Maximized"  # "Windowed" | "Maximized" | "Fullscreen"

[window.class]
instance = "Alacritty"
general = "Alacritty"

[font]
normal = { family = "Moralerspace Argon HW", style = "Regular" }
size = 20.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_timeout = 5
unfocused_hollow = false
thickness = 0.3

[terminal]
shell = { program = "/usr/bin/fish" }

[mouse]
hide_when_typing = true
