[general]
import = [ 
  # "themes/themes/synthwave_84.toml",
  "themes/themes/nord.toml",
]

live_config_reload = true

[terminal]
shell = "fish"

[font]
size = 16.0

[font.normal]
family = "Moralerspace Neon HWNF"

[window]
opacity = 0.8
blur = false
dimensions = { columns = 130, lines = 30 }
dynamic_padding = true
decorations = "full"  # None | Full
startup_mode = "windowed"  # "Windowed" | "Maximized" | "Fullscreen"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 15
thickness = 0.15
unfocused_hollow = true

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true
