[general]
import = [ 
  "themes/themes/nord.toml",
  # "themes/themes/synthwave_84.toml",
]
live_config_reload = true

[window]
dimensions = { columns = 150, lines = 38 }
dynamic_padding = true
decorations = "full"  # None | Full
opacity = 0.85
blur = false
startup_mode = "windowed"  # "Windowed" | "Maximized" | "Fullscreen"

[font]
normal = { family = "Moralerspace Neon HWNF", style = "Regular" }
size = 16.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_timeout = 15
unfocused_hollow = false
thickness = 0.3

[terminal]
shell = { program = "/usr/bin/fish", args = [] }

[mouse]
hide_when_typing = true
