"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
package = { disabled = true, display_private = false, format = "is [$symbol$version]($style) ", style = "208 bold", symbol = "📦 ", version_format = "v${raw}" }

# [time]
# disabled = true
# time_format = '%T'
